export const CATEGORIES = [
  ['love-loss', 'Love & loss'],
  ['faith-doubt', 'Faith & doubt'],
  ['family-belonging', 'Family & belonging'],
  ['success-worth', 'Success & worth'],
  ['anger-justice', 'Anger & justice'],
  ['meaning-mortality', 'Meaning & mortality']
].map(([id, name]) => ({ id, name }));

export const SOURCES = [
  { id:'src-jesus', title:'Matthew 5:43–48', authorOrAttribution:'Gospel according to Matthew', reference:'5:43–48', editionOrTranslator:'NRSVUE', url:'https://www.biblegateway.com/passage/?search=Matthew%205%3A43-48&version=NRSVUE', accessedAt:'2026-10-05' },
  { id:'src-paul', title:'Romans 12', authorOrAttribution:'Paul the Apostle', reference:'12:1–21', editionOrTranslator:'NRSVUE', url:'https://www.biblegateway.com/passage/?search=Romans%2012&version=NRSVUE', accessedAt:'2026-10-05' },
  { id:'src-peter', title:'John 21:15–19', authorOrAttribution:'Gospel according to John', reference:'21:15–19', editionOrTranslator:'NRSVUE', url:'https://www.biblegateway.com/passage/?search=John%2021%3A15-19&version=NRSVUE', accessedAt:'2026-10-05', attributionNote:'A narrative about Peter, not a text authored by Peter.' },
  { id:'src-abraham-christian', title:'Romans 4', authorOrAttribution:'Paul the Apostle', reference:'4:1–25', editionOrTranslator:'NRSVUE', url:'https://www.biblegateway.com/passage/?search=Romans%204&version=NRSVUE', accessedAt:'2026-10-05', attributionNote:'A Christian reception of Abraham; Abraham is also central to Jewish and Islamic traditions.' },
  { id:'src-moses', title:'Deuteronomy 30', authorOrAttribution:'Hebrew Bible', reference:'30:11–20', editionOrTranslator:'NRSVUE', url:'https://www.biblegateway.com/passage/?search=Deuteronomy%2030%3A11-20&version=NRSVUE', accessedAt:'2026-10-05', attributionNote:'Used here through a Christian reception while retaining its Jewish scriptural context.' },
  { id:'src-luther', title:'Concerning Christian Liberty', authorOrAttribution:'Martin Luther', reference:'Primary source excerpt, 1520', url:'https://media.bloomsbury.com/rep/files/primary-source-74-martin-luther-concerning-christian-liberty.pdf', accessedAt:'2026-10-05' },
  { id:'src-buddha', title:'Dhammapada: Pairs', authorOrAttribution:'Traditionally attributed teachings of the Buddha', reference:'verses 1–20', editionOrTranslator:'Acharya Buddharakkhita', url:'https://www.accesstoinsight.org/tipitaka/kn/dhp/dhp.01.budd.html', accessedAt:'2026-10-05' },
  { id:'src-ashoka', title:'The Edicts of King Ashoka', authorOrAttribution:'King Ashoka', reference:'Rock Edicts I–XIV', editionOrTranslator:'Ven. S. Dhammika', url:'https://www.accesstoinsight.org/lib/authors/dhammika/wheel386.html', accessedAt:'2026-10-05' },
  { id:'src-nagarjuna', title:'Nāgārjuna', authorOrAttribution:'Stanford Encyclopedia of Philosophy', reference:'Emptiness and dependent existence', url:'https://plato.stanford.edu/entries/nagarjuna/', accessedAt:'2026-10-05', attributionNote:'Scholarly context for a complex philosophical tradition.' },
  { id:'src-bodhidharma', title:'The Zen Teaching of Bodhidharma', authorOrAttribution:'Texts traditionally attributed to Bodhidharma', reference:'Outline of Practice', url:'https://terebess.hu/zen/bodhidharma-eng.html', accessedAt:'2026-10-05', attributionNote:'Traditional attributions are historically uncertain.' },
  { id:'src-dalai-lama', title:'Compassion and the Individual', authorOrAttribution:'Tenzin Gyatso, 14th Dalai Lama', reference:'Compassion and human values', url:'https://www.dalailama.com/messages/compassion-and-human-values/compassion', accessedAt:'2026-10-05' },
  { id:'src-ibrahim', title:'Qur’an 26:83–89', authorOrAttribution:'Qur’an', reference:'26:83–89', url:'https://quran.com/26/83-89', accessedAt:'2026-10-05' },
  { id:'src-malcolm', title:'The Ballot or the Bullet', authorOrAttribution:'Malcolm X', reference:'Detroit speech delivered 12 April 1964', url:'https://americanradioworks.publicradio.org/features/blackspeech/mx.html', accessedAt:'2026-10-05', attributionNote:'The page places this speech within Malcolm X’s changing 1964 views, including the wider outlook he described after the Hajj.' },
  { id:'src-rabia', title:'Rābi‘ah al-‘Adawiyah', authorOrAttribution:'EBSCO Research Starters', reference:'Biography and research bibliography', url:'https://www.ebsco.com/research-starters/biography/rabiah-al-adawiyah', accessedAt:'2026-10-05', attributionNote:'Many sayings circulate through later tradition rather than secure verbatim records.' },
  { id:'src-rumi', title:'Rumi’s Teachings', authorOrAttribution:'Encyclopaedia Iranica', reference:'Masnavi, Fihi ma fihi, and teaching context', url:'https://www.iranicaonline.org/articles/rumi-jalal-al-din-teachings/', accessedAt:'2026-10-05' },
  { id:'src-ghazali', title:'al-Ghazali', authorOrAttribution:'Stanford Encyclopedia of Philosophy', reference:'Ethics of the Revival of the Religious Sciences', url:'https://plato.stanford.edu/entries/al-ghazali/', accessedAt:'2026-10-05' },
  { id:'src-ibn-arabi', title:'Muhyiddin Ibn Arabi', authorOrAttribution:'Muhyiddin Ibn Arabi Society', reference:'Life and writings', url:'https://ibnarabisociety.org/ibn-arabi/', accessedAt:'2026-10-05' },
  { id:'src-abu-hanifa', title:'Abū Ḥanīfa', authorOrAttribution:'Encyclopaedia Iranica', reference:'Life, controversy, and legal reasoning', url:'https://www.iranicaonline.org/articles/abu-hanifa-noman-b/', accessedAt:'2026-10-05' }
];

const P = (id, figureId, religion, displayName, lensLabel, lensDescription, frame, move, caution, value, practice, rationale, sourceId, basisType='modern-application') => ({ id, figureId, religion, displayName, lensLabel, lensDescription, frame, move, caution, value, practice, rationale, sourceIds:[sourceId], basisType });

export const PERSPECTIVES = [
  P('buddhism-gautama','gautama','buddhism','Siddhartha Gautama','The Buddha','Craving, suffering, impermanence, and ethical practice.','A Buddha-inspired reading separates unavoidable pain from the suffering intensified by grasping and aversion.','observe what the mind keeps demanding before treating that demand as a command.','Non-attachment does not mean numbness or passive acceptance of harm.','clarity, compassion, and less clinging','Notice the strongest recurring thought, name it without judgment, and wait before acting on it.','The Dhammapada connects mental habits with suffering and treats practice, not mere recitation, as decisive.','src-buddha'),
  P('buddhism-ashoka','ashoka','buddhism','King Ashoka','Buddhist ruler','Remorse translated into conduct, restraint, and public responsibility.','An Ashoka-inspired reading tests conviction by the conduct it produces.','turn remorse, anger, or status into a concrete reduction of harm.','Good intentions do not cancel consequences, and remorse without changed behavior stays incomplete.','responsibility and practical non-harm','Choose one repair you can make without demanding praise, access, or forgiveness in return.','Ashoka’s edicts present moral concern through restraint, welfare, self-examination, and respect across convictions.','src-ashoka'),
  P('buddhism-nagarjuna','nagarjuna','buddhism','Nagarjuna','Madhyamaka philosopher','Dependent existence and freedom from rigid identities.','A Nagarjuna-inspired reading questions the fixed labels that make a painful event seem like an eternal essence.','look for the conditions producing the story instead of declaring that the story is what you are.','Emptiness is not nihilism; actions and consequences still matter conventionally.','intellectual humility and freedom from rigid views','Rewrite one absolute sentence using conditions: replace “I am” with “I feel this when…”.','Nagarjuna’s analysis challenges intrinsic, independent identity and shows how phenomena arise dependently.','src-nagarjuna'),
  P('buddhism-bodhidharma','bodhidharma','buddhism','Bodhidharma','Chan teacher','Direct practice, endurance, and freedom from performing wisdom.','A Bodhidharma-inspired reading distrusts clever explanations that never alter conduct.','meet the difficulty directly and practice the next right action without making an identity out of insight.','Traditional texts associated with Bodhidharma have uncertain attribution and should not be treated as transcripts.','practice and steadiness','Spend ten quiet minutes with the feeling, then do one necessary task without narrating yourself as hero or victim.','The traditionally attributed Outline of Practice emphasizes meeting conditions and putting understanding into practice.','src-bodhidharma','tradition'),
  P('buddhism-tenzin','tenzin-gyatso','buddhism','Tenzin Gyatso','14th Dalai Lama','Compassion, interdependence, and emotional discipline.','A Dalai Lama-inspired reading treats compassion as clear-eyed concern rather than sentimental approval.','widen the frame enough to include your suffering, other people’s humanity, and the consequences of action.','Compassion can coexist with firm boundaries and does not require agreement.','shared human dignity and disciplined compassion','Describe the situation once from your view and once from the other person’s possible fears, without excusing harm.','His published teaching presents compassion as grounded in our shared desire for happiness and freedom from suffering.','src-dalai-lama'),

  P('christianity-jesus','jesus','christianity','Jesus Christ','Gospel-centered Christian lens','Mercy, love beyond reciprocity, and resistance to retaliation.','A Jesus-inspired reading asks what love looks like when affection, status, or fairness is not returned.','refuse revenge while telling the truth and protecting the vulnerable.','Mercy does not require restored access, trust, or pretending wrongdoing is harmless.','love of neighbor and enemy','Remove one action whose main purpose is humiliation, then choose a truthful boundary instead.','Matthew 5 challenges love limited to people who reciprocate and confronts retaliatory moral imagination.','src-jesus'),
  P('christianity-paul','paul','christianity','Paul the Apostle','Pauline Christian lens','Grace, transformed character, and life within a community.','A Pauline reading asks whether your next action conforms to a renewed life rather than the pressure of the moment.','answer harm without becoming governed by it and locate personal freedom inside obligations to others.','Grace is not permission to evade responsibility; transformation becomes visible in conduct.','grace, sober judgment, and communal responsibility','Choose an action you would still defend if the affected people were present in the room.','Romans 12 joins transformed thinking, sober self-assessment, mutual obligation, peace, and resistance to vengeance.','src-paul'),
  P('christianity-peter','peter','christianity','Peter the Apostle','Petrine narrative lens','Failure, humility, restoration, and returning to responsibility.','A Peter-inspired reading does not treat failure as the last truthful thing about a person.','acknowledge what happened, accept the cost of repair, and return to responsibility without demanding instant restoration.','A second chance is a call to service, not proof that trust must return immediately.','humility and responsible restoration','Name what you did or endured plainly, then identify the next responsibility that is actually yours.','John 21 narrates Peter’s restoration after failure and connects renewed relationship with renewed responsibility.','src-peter','narrative'),
  P('christianity-abraham','abraham','christianity','Abraham','Christian reading','Trust amid uncertainty, promise, and a future not fully controlled.','A Christian reading of Abraham takes uncertainty seriously without making control the condition of trust.','act faithfully with limited knowledge instead of demanding a guaranteed outcome first.','Trust should not be used to baptize recklessness or silence evidence.','faithful action under uncertainty','Write down what you know, what you hope, and the honest risk you must carry; do not merge the three.','Romans 4 interprets Abraham through trust and promise, within a specifically Christian reception.','src-abraham-christian'),
  P('christianity-moses','moses','christianity','Moses','Christian reading','Freedom joined to obligation, justice, and communal life.','A Christian reading of Moses treats freedom as the capacity to choose a life-giving obligation, not merely escape restraint.','ask which choice serves life, justice, and the people affected beyond your immediate emotion.','Rules can be misused; moral responsibility includes understanding whom a rule protects and harms.','covenant responsibility and life-giving choice','List everyone affected by the decision and one obligation you owe each of them.','Deuteronomy 30 frames moral decision as a consequential choice of life within covenantal responsibility.','src-moses'),
  P('christianity-luther','martin-luther','christianity','Martin Luther','Lutheran lens','Grace, conscience, and freedom from earning human worth.','A Luther-inspired reading challenges the exhausting attempt to purchase worth through achievement or approval.','receive dignity as gift and let freedom become service rather than self-justification.','Freedom of conscience is not freedom from accountability to neighbors.','grace, conscience, and service','Do one good act that cannot improve your image and tell no one about it.','The Freedom of a Christian holds together freedom grounded in faith and willing service to one’s neighbor.','src-luther'),

  P('islam-ibrahim','abraham','islam','Ibrahim (Abraham)','Qur’anic lens','Devotion to God, wisdom, trust, and upright action.','An Ibrahim-inspired reading redirects the demand for a guaranteed outcome toward a prayer for wisdom and righteous company.','choose the next upright act while leaving what you cannot control to God.','Do not label every loss a divine message or promise that devotion will produce the desired result.','wisdom, devotion, and integrity','Name one decision you can make with integrity today, independent of another person’s response.','Qur’an 26:83 records Ibrahim asking God for wisdom and to be joined with the righteous.','src-ibrahim'),
  P('islam-malcolm','malcolm-x','islam','Malcolm X','Post-1964 Muslim lens','Dignity, justice, agency, and willingness to revise convictions.','A Malcolm X-inspired reading refuses humiliation as a permanent social position and treats honest revision as strength.','recover agency, name injustice clearly, and revise a view when wider experience exposes its limits.','Dignity should not become an excuse for indiscriminate hostility or a refusal to change.','dignity, truth, and disciplined self-revision','State the injustice in one sentence, then choose an action that increases your agency rather than their control.','His 1964 speeches joined dignity and political agency; his later life also demonstrates substantive revision of belief.','src-malcolm'),
  P('islam-rabia','rabia-al-adawiyya','islam','Rabi’a al-Adawiyya','Sufi devotional lens','Love of God beyond bargaining for reward or fear of punishment.','A Rabi’a-inspired reading asks whether devotion has become a bargain: goodness offered only to purchase a result.','act from love of God rather than treating piety, affection, or sacrifice as leverage.','Many sayings attributed to Rabi’a come through later tradition, so this is a devotional lens rather than a verbatim reply.','unbargained devotion and sincerity','Do one act of care without using it to secure affection, praise, or moral superiority.','The devotional tradition surrounding Rabi’a emphasizes love of God beyond calculation of reward and punishment.','src-rabia','tradition'),
  P('islam-rumi','rumi','islam','Jalal al-Din Rumi','Sufi poetic lens','Love, transformation, longing, and the education of the ego.','A Rumi-inspired reading lets longing expose the ego without romanticizing every wound as spiritually necessary.','allow loss or desire to enlarge perception rather than making possession the proof of love.','Poetic transformation does not make abuse beautiful, deserved, or safe.','transformative love and humility','Write what the longing reveals about you without turning the other person into a symbol or prize.','Rumi’s major works belong to an Islamic Sufi context in which love and longing transform the seeker.','src-rumi'),
  P('islam-ghazali','al-ghazali','islam','Abu Hamid al-Ghazali','Sunni ethical and Sufi lens','Intention, self-examination, disciplined character, and accountability.','An al-Ghazali-inspired reading examines the hidden intention beneath a respectable explanation.','separate the good you claim to seek from pride, display, appetite, or fear that may be steering you.','Self-examination should produce honesty and reform, not obsessive self-condemnation.','sincere intention and trained character','Before acting, finish the sentence “I want people to see me as…” and test whether that motive should lead.','Al-Ghazali’s ethical project in the Revival emphasizes disciplined character, intention, and knowledge ordered toward practice.','src-ghazali'),
  P('islam-ibn-arabi','ibn-arabi','islam','Ibn Arabi','Sufi metaphysical lens','Humility before partial viewpoints, divine reality, and the education of perception.','An Ibn Arabi-inspired reading distrusts the ego’s claim that its present viewpoint contains the whole reality.','hold firm convictions with humility about how much of another person, God, or the future you can see.','Humility about perspective does not mean every claim is equally true or every action equally just.','humility, receptivity, and widened perception','Name one fact that could complicate your current story without erasing what you know happened.','Ibn Arabi’s writings explore knowledge, divine reality, and the limits and transformations of human perception.','src-ibn-arabi'),
  P('islam-abu-hanifa','abu-hanifa','islam','Abu Hanifa','Sunni legal-ethical lens','Deliberation, rights, obligations, fairness, and limits of certainty.','An Abu Hanifa-inspired reading slows moral confidence long enough to distinguish fact, inference, right, and obligation.','reason carefully about who is owed what before turning a strong feeling into a sweeping judgment.','A historical jurist should not be made to issue invented rulings on modern facts he never considered.','fairness, deliberation, and accountable judgment','Make four columns—facts, assumptions, rights, obligations—and put every claim in only one.','Abu Hanifa’s legacy is associated with systematic legal reasoning and a durable tradition of juristic deliberation.','src-abu-hanifa')
];

const Q = (id, categoryId, title, premise, aliases, keywords, featured, opening, application, feeling, shortProblem, rationaleFocus, practiceLead) => ({ id, categoryId, title, premise, aliases, keywords, featured, opening, application, feeling, shortProblem, rationaleFocus, practiceLead });

export const QUESTIONS = [
  Q('q01-replaced','love-loss','My partner left me for someone else. Why wasn’t I enough?','You are dealing with rejection and comparison. This question does not assume your former partner cheated or that you did something wrong.',['girlfriend left me','boyfriend left me','dumped for someone else','replaced after breakup'],['breakup','rejection','comparison','enough'],true,'Being left can turn grief into a verdict about your worth.','you can grieve without treating another person’s choice as an objective measurement of your value.','the loss and the comparison','romantic rejection','how comparison turns pain into identity','For the next seven days, stop one behavior that renews the comparison.'),
  Q('q02-cheated','love-loss','I cheated on someone I love. Am I a bad person—or just avoiding responsibility?','You caused a breach of trust. Remorse matters most when it produces honesty, changed conduct, and respect for the harmed person’s choices.',['i cheated','unfaithful to my partner','betrayed my partner'],['infidelity','guilt','remorse','accountability'],false,'Guilt can either clarify the harm or become a performance centered on your pain.','you can name the betrayal without reducing your whole identity to it, then accept consequences you do not control.','guilt and fear of losing the relationship','betrayal and remorse','the difference between remorse, identity, and repair','Tell the truth without asking the harmed person to comfort you.'),
  Q('q03-forgive','love-loss','Do I owe forgiveness to someone who isn’t sorry?','Forgiveness, reconciliation, restored trust, and renewed access are separate choices. Nothing here requires returning to someone unsafe.',['no apology','forgive someone','wont apologize','not sorry'],['forgiveness','apology','trust','boundaries'],true,'Pressure to forgive can hide the real work of naming harm and deciding what future contact is wise.','you can release the wish to be ruled by the injury while keeping boundaries and refusing false reconciliation.','anger and unresolved hurt','forgiveness without apology','why mercy and boundaries are not opposites','Define forgiveness, trust, and access separately before deciding what you offer.'),
  Q('q04-suffering','faith-doubt','If God is good, why do good people suffer?','The question begins with a theistic premise. Buddhist perspectives may reframe suffering without proposing a creator God.',['why suffering','innocent people suffer','problem of evil','why does god allow pain'],['god','evil','suffering','innocence'],true,'Suffering resists explanations that make pain sound tidy, deserved, or intellectually solved.','you can seek meaning and responsibility without pretending to know why every tragedy happened.','grief and moral bewilderment','undeserved suffering','how each tradition relates explanation, compassion, and action','Separate the explanation you want from the help a suffering person needs now.'),
  Q('q05-inherited-belief','faith-doubt','Do I believe this—or was I just raised to believe it?','Honest examination can respect a tradition and family without treating inherited belief as automatically true or false.',['raised religious','questioning my faith','inherited belief','parents religion'],['belief','doubt','family','tradition'],false,'Inherited belief can feel either like a gift or like a script you never chose.','you can examine evidence, practice, and consequence without performing certainty for family or rebellion for an audience.','doubt and divided loyalty','inherited religion','how honest inquiry can coexist with belonging','Write one belief you hold, why you hold it, and what could change your mind.'),
  Q('q06-good-without-religion','faith-doubt','Can I be a good person without being religious?','This asks about ethical conduct. Each tradition may also make separate claims about spiritual fulfillment, liberation, or relationship with God.',['atheist morality','good without god','moral without religion'],['atheism','morality','goodness','religion'],true,'People outside formal religion plainly make costly moral choices, while traditions ask questions larger than public respectability.','you can evaluate character through conduct while honestly hearing each tradition’s deeper account of the good life.','uncertainty about moral worth','goodness outside religion','the relation between moral action, motive, and spiritual ends','Choose one costly good action and examine the reason you are willing to do it.'),
  Q('q07-parents','family-belonging','My parents sacrificed for me. Do they get to choose my life?','Gratitude creates real responsibilities, but it does not automatically transfer ownership of an adult child’s conscience or future.',['parents control my life','family expectations','parents choose my career','owe my parents'],['parents','career','gratitude','autonomy'],true,'Sacrifice can create gratitude while also becoming a language of control.','you can honor what was given, identify what you truly owe, and still take responsibility for a life only you can live.','love, guilt, and pressure','family sacrifice and autonomy','how gratitude differs from surrendering moral agency','Name one debt of gratitude you accept and one decision that remains yours.'),
  Q('q08-interfaith-love','family-belonging','I love someone from another religion. Is love enough?','Love matters, but shared life also includes worship, family expectations, children, law, and practices that deserve direct discussion.',['interfaith relationship','different religion relationship','interfaith marriage'],['love','marriage','religion','family'],false,'Affection can postpone disagreements that become concrete when two lives are joined.','you can honor love by discussing commitments and non-negotiables before promises make honesty more costly.','hope and fear of incompatibility','interfaith love','how love relates to truth, community, and commitment','Discuss worship, children, family pressure, and conversion without assuming love will answer for you.'),
  Q('q09-envy','family-belonging','My friend succeeded, and I hate how jealous I feel.','An emotion is not yet an action. The question is what jealousy reveals and what habits either feed or transform it.',['jealous of my friend','friend succeeded','envious of friend','comparison with friend'],['jealousy','envy','success','friendship'],true,'A friend’s success can expose desires and insecurities you would rather not admit.','you can tell the truth about envy without punishing your friend or pretending their good fortune caused your lack.','envy and shame','jealousy toward a friend','how comparison distorts friendship and self-knowledge','Congratulate your friend without mentioning yourself, then name what you actually want.'),
  Q('q10-ambition','success-worth','Is wanting to be rich ambition—or greed with better branding?','Money is not judged only by amount. Motive, means, obligations, use, and the harms accepted along the way all matter.',['want to be rich','money ambition','wealth or greed'],['money','wealth','ambition','greed'],false,'Ambition often presents itself as neutral even when it requires other people to absorb its cost.','you can examine how wealth is pursued, what it is for, and what amount of “enough” would actually govern desire.','hunger for security and status','ambition and greed','how motive, method, and obligation expose desire','Define enough in numbers and obligations before success keeps moving the boundary.'),
  Q('q11-failure','success-worth','I worked hard and still failed. What was the point?','This concerns a real setback in work, study, or craft. Effort can have value without guaranteeing the result you wanted.',['failed exam','effort wasted','worked hard and failed','failure'],['failure','effort','exam','work'],false,'Failure can make past effort look meaningless because it did not purchase the desired result.','you can grieve the outcome, learn what the effort changed, and decide whether persistence or release is now wiser.','disappointment and wasted effort','hard work without success','how outcomes relate to character and wise persistence','List what the effort built, what it failed to build, and what evidence should guide the next attempt.'),
  Q('q12-exhaustion','success-worth','Am I lazy, or am I exhausted from trying to deserve rest?','This reflection cannot diagnose burnout or depression. Persistent exhaustion deserves practical and, when needed, professional attention.',['i am exhausted','too tired to work','lazy or burned out','deserve rest'],['rest','burnout','lazy','productivity'],false,'A culture of performance can turn rest into evidence for the prosecution.','you can examine capacity, avoidance, health, and obligation without making productivity the measure of human worth.','exhaustion and self-accusation','rest and deservedness','how discipline differs from contempt for human limits','For one week, record sleep, obligations, avoidance, and energy before calling yourself lazy.'),
  Q('q13-revenge','anger-justice','Someone humiliated me. Why shouldn’t I make them hurt too?','Retaliation may feel like restored balance. Justice, protection, accountability, and revenge are related but different aims.',['want revenge','humiliated me','get even','hurt them back'],['revenge','anger','humiliation','justice'],false,'Humiliation creates a powerful urge to reverse the roles and make the other person small.','you can pursue protection and accountability without handing your conduct to the person who injured your pride.','rage and wounded dignity','humiliation and revenge','how justice separates itself from retaliatory pleasure','Delay the retaliatory act, document the harm, and state the just outcome you would accept without cruelty.'),
  Q('q14-lie','anger-justice','Is lying wrong if the truth will hurt someone?','This distinguishes compassionate timing and safety from deception used for convenience, control, or avoiding deserved consequences.',['white lie','painful truth','honesty hurts','lie to protect someone'],['lying','truth','honesty','harm'],false,'“I did not want to hurt them” can describe compassion, fear, convenience, or control.','you can ask who benefits from concealment, what the listener is owed, and whether truth can be offered with care and safety.','fear of causing pain','harmful truth and protective lies','how truth, intention, and obligation interact','Write the truth, the likely harm, who benefits from silence, and a safer honest way to speak.'),
  Q('q15-unfair-world','anger-justice','Why should I play fair when dishonest people keep winning?','Integrity does not require passivity toward corrupt rules. Personal conduct and collective action against unfair systems belong together.',['cheaters win','corrupt people succeed','unfair system','dishonest people'],['fairness','corruption','integrity','justice'],false,'Watching dishonest people prosper can make integrity feel like self-sabotage.','you can refuse corruption while organizing, documenting, and changing the conditions that reward it.','cynicism and disadvantage','dishonesty that appears rewarded','why integrity needs strategy and solidarity','Choose one unfair condition you can document or challenge with others instead of copying it alone.'),
  Q('q16-fear-death','meaning-mortality','I’m scared of dying. How am I supposed to live normally?','Fear of death is human. This is philosophical reflection, not clinical assessment; severe or persistent panic deserves qualified support.',['fear of death','scared of dying','mortality anxiety','afterlife fear'],['death','fear','mortality','afterlife'],false,'Awareness of death can either narrow life into panic or sharpen attention to what deserves it.','you can face mortality in measured doses while returning to relationships, duties, and practices available today.','fear and uncertainty','fear of death','how finitude changes attention and value','Name one postponed act of care that mortality makes more urgent, and do it this week.'),
  Q('q17-forgotten','meaning-mortality','If everyone eventually forgets me, does my life matter?','Meaning need not depend on fame, permanent memory, or having an audience large enough to prove that a life counted.',['everyone will forget me','legacy','life insignificant','does my life matter'],['meaning','legacy','forgotten','significance'],false,'The desire to be remembered can make ordinary care look too small to count.','you can measure meaning through truthful relationship and consequence rather than imagined permanence.','insignificance and longing for legacy','being forgotten','how finite actions can matter without permanent fame','Do one useful thing whose value survives even if your name is never attached to it.'),
  Q('q18-desire','meaning-mortality','Is desire the problem—or is shame about desire the problem?','Desire includes many forms of wanting. Ethical reflection must consider consent, attachment, honesty, restraint, and consequences without shaming identity.',['desire and shame','lust','wanting someone','ashamed of desire'],['desire','shame','attachment','consent'],false,'Desire can reveal vitality and connection, but it can also turn another person into an instrument or become a demand.','you can acknowledge wanting without granting it authority over consent, honesty, responsibility, or your whole identity.','desire and shame','desire under shame','how wanting, attachment, restraint, and dignity relate','Name the desire plainly, then list whose consent, trust, and well-being your response must honor.')
];

const order = Object.fromEntries(PERSPECTIVES.map((p, i) => [p.id, i]));

export const ANSWERS = QUESTIONS.flatMap(question => PERSPECTIVES.map(perspective => ({
  id: `${question.id}--${perspective.id}`,
  questionId: question.id,
  perspectiveId: perspective.id,
  kind: 'interpretation',
  basisType: perspective.basisType,
  thesis: `${perspective.value[0].toUpperCase()}${perspective.value.slice(1)} before impulse.`,
  body: `${question.opening} ${perspective.frame} From this perspective, ${perspective.move} Applied here, that means ${question.application} ${perspective.caution}`,
  practice: `${question.practiceLead} ${perspective.practice}`,
  rationale: `${perspective.rationale} Applied to this question, it focuses on ${question.rationaleFocus}.`,
  sourceIds: perspective.sourceIds,
  attributionNote: 'This is a modern editorial interpretation inspired by the cited material, not a quotation or personal reply.',
  reviewStatus: 'editorial-component-review',
  sortOrder: order[perspective.id]
})));

export const FIGURES = [
  ['gautama','Siddhartha Gautama',['Buddha','Gautama Buddha'],'Teacher at the center of Buddhist traditions, associated with a path addressing suffering through ethical conduct, meditation, and insight.'],
  ['ashoka','King Ashoka',['Ashoka'],'Mauryan ruler remembered for edicts connecting remorse, non-harm, welfare, and respect among traditions.'],
  ['nagarjuna','Nagarjuna',['Nāgārjuna'],'Influential Buddhist philosopher associated with Madhyamaka analysis of emptiness and dependent existence.'],
  ['bodhidharma','Bodhidharma',[],'Traditionally remembered as an early transmitter of Chan Buddhism, with several teachings attributed to him uncertainly.'],
  ['tenzin-gyatso','Tenzin Gyatso',['14th Dalai Lama','Dalai Lama'],'Tibetan Buddhist teacher whose public work emphasizes compassion, interdependence, and universal human values.'],
  ['jesus','Jesus Christ',['Jesus'],'Central figure of Christianity, presented in the Gospels through teachings on God, love, mercy, justice, and the kingdom of God.'],
  ['paul','Paul the Apostle',['Saint Paul'],'Early Christian missionary and letter writer whose work shaped Christian accounts of grace, community, and transformed life.'],
  ['peter','Peter the Apostle',['Saint Peter'],'Early disciple of Jesus remembered through failure, restoration, leadership, and responsibility in Christian narratives.'],
  ['abraham','Abraham',['Ibrahim'],'Shared ancestral figure in Jewish, Christian, and Islamic traditions. This project keeps separate Christian and Islamic interpretive lenses.'],
  ['moses','Moses',['Musa'],'Central figure of Jewish scripture, also received within Christianity and Islam; this project’s listed lens is explicitly Christian reception.'],
  ['martin-luther','Martin Luther',[],'Sixteenth-century Christian reformer whose writings treat faith, conscience, grace, freedom, and service.'],
  ['malcolm-x','Malcolm X',['El-Hajj Malik El-Shabazz'],'Muslim minister and human-rights activist whose changing thought joined dignity, justice, internationalism, and self-revision.'],
  ['rabia-al-adawiyya','Rabi’a al-Adawiyya',['Rabia'],'Early Muslim ascetic and devotional figure associated in later Sufi tradition with uncalculated love of God.'],
  ['rumi','Jalal al-Din Rumi',['Rumi'],'Thirteenth-century Muslim scholar and Sufi poet whose work explores love, longing, transformation, and the divine.'],
  ['al-ghazali','Abu Hamid al-Ghazali',['al-Ghazali'],'Influential Sunni theologian, jurist, philosopher, and mystic whose ethics emphasize intention, practice, and purification of character.'],
  ['ibn-arabi','Ibn Arabi',['Muhyiddin Ibn Arabi'],'Influential Sufi thinker whose works explore divine reality, knowledge, imagination, and transformed perception.'],
  ['abu-hanifa','Abu Hanifa',[],'Early Muslim jurist associated with the Hanafi school and a lasting tradition of legal reasoning and deliberation.']
].map(([id,name,aliases,bio]) => ({ id,name,aliases,bio, perspectiveIds:PERSPECTIVES.filter(p=>p.figureId===id).map(p=>p.id), bioSourceIds:PERSPECTIVES.filter(p=>p.figureId===id).flatMap(p=>p.sourceIds) }));

export const RELIGIONS = {
  buddhism: { name:'Buddhism', count:5 },
  christianity: { name:'Christianity', count:6 },
  islam: { name:'Islam', count:7 }
};

export function questionById(id) { return QUESTIONS.find(q => q.id === id); }
export function perspectiveById(id) { return PERSPECTIVES.find(p => p.id === id); }
export function figureById(id) { return FIGURES.find(f => f.id === id); }
export function sourceById(id) { return SOURCES.find(s => s.id === id); }
export function answersFor(questionId) { return ANSWERS.filter(a => a.questionId === questionId).sort((a,b) => a.sortOrder-b.sortOrder); }
